# We use Amazon Corretto as a base (JDK 17 on Alpine)
FROM amazoncorretto:17-alpine
# Working directory within the container
WORKDIR /app
# Copy the JAR generated by Maven to your machine/Jenkins
# Ensure that target/*.jar already exists before running docker build
COPY target/aquarius-configuration-server.jar app.jar
# Set time zone
ENV TZ=America/Mexico_City
RUN apk add --no-cache tzdata && cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# Expose the port where your Spring Boot is listening
EXPOSE 8888
# Boot command
ENTRYPOINT ["java", "-jar", "/app/app.jar"]